build and extract: now detect cpio and gzip errors.

diff --git a/cpustress/build/build b/cpustress/build/build
--- a/cpustress/build/build
+++ b/cpustress/build/build
@@ -74,6 +74,11 @@ echo "Making cpio archive..."
 # -H (synonym of --format) does not work with old bsdcpio.
 # --owner (synonym of -R) might be GNU-only.
 find . | LC_ALL=C sort | sed -f ../filelist-tmp.sed | cpio -o --format newc -R root:root >../initrd
+STATUS="$?"
+if [ "$STATUS" -ne "0" ]; then
+    echo "ERROR: cpio error with exit code $STATUS."
+    exit 1
+fi
 
 rm ../filelist-tmp.sed
 
@@ -93,9 +98,19 @@ fi
 
 if [ "X$P7ZIP" != "X" ]; then
     ${P7ZIP} a -tgzip -mx=9 initrd.gz initrd
+    STATUS="$?"
+    if [ "$STATUS" -ne "0" ]; then
+        echo "ERROR: ${P7ZIP} error with exit code $STATUS."
+        exit 1
+    fi
 else
     echo "7-zip is not found. Using gzip instead..."
     gzip -9 -v initrd
+    STATUS="$?"
+    if [ "$STATUS" -ne "0" ]; then
+        echo "ERROR: gzip error with exit code $STATUS."
+        exit 1
+    fi
 fi
 
 rm -f initrd
diff --git a/cpustress/build/extract b/cpustress/build/extract
--- a/cpustress/build/extract
+++ b/cpustress/build/extract
@@ -6,7 +6,7 @@
 # <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
 #
 # Written by Explorer.
-# Last updated on 6 July 2013.
+# Last updated on 13 August 2013.
 
 # Change working directory to the directory of the script.
 cd `dirname $0`
@@ -27,5 +27,10 @@ echo "Extracting initrd.gz..."
 gzip -d -v -c initrd.gz >build-initrd/initrd
 cd build-initrd
 cpio -i -m -d -u <initrd
+STATUS="$?"
+if [ "$STATUS" -ne "0" ]; then
+    echo "ERROR: cpio error with exit code $STATUS."
+    exit 1
+fi
 rm initrd
 echo "Done."
