Multiple changes in initrd 'build' script: (1) Add 'cpio --version' check so we don't invoke incompatible cpio. (2) Use poor man's 'which' command. (3) Improve filename sorting when creating cpio.

diff --git a/cpustress/build/build b/cpustress/build/build
--- a/cpustress/build/build
+++ b/cpustress/build/build
@@ -11,7 +11,7 @@
 # Change working directory to the directory of the script.
 cd `dirname $0`
 
-# Execute the prepare script when needed
+# Execute the prepare script when needed.
 if [ ! -d "build-initrd/dev" ]; then
     echo "Executing ./prepare ..."
     sh ./prepare
@@ -34,6 +34,50 @@ if [ "$HAS_ERRORS" = "true" ]; then
     echo "There are important directories missing from 'build-initrd'. Aborting." >&2
     exit 1
 fi
+
+# Check cpio.
+# I support only GNU cpio and bsdcpio. Others such as Solaris cpio simply
+# won't work here.
+case `cpio --version | sed -n -e '1 p'` in
+    *GNU* | *bsdcpio*)
+        ;;
+    *)
+        echo "ERROR: This script needs a GNU cpio or bsdcpio." >&2
+        exit 1
+esac
+
+# Check 7-zip and gzip.
+# 7-zip is preferred because it can produce a smaller file size than gzip.
+# 7z and 7za work here, but 7zr doesn't.
+
+# Save IFS
+SAVED_IFS=$IFS
+
+# Poor man's 'which' command
+IFS=:
+P7ZIP=""
+GZIP=""
+for n in 7z 7za; do
+    for d in $PATH ; do
+        if [ -x "$d/$n" ]; then
+            P7ZIP="$n"
+            break
+        fi
+    done
+done
+for d in $PATH ; do
+    if [ -x "$d/gzip" ]; then
+        GZIP="gzip"
+        break
+    fi
+done
+if [ "X$P7ZIP" = "X" ] && [ "X$GZIP" = "X" ]; then
+    echo "ERROR: This script needs p7zip or gzip." >&2
+    exit 1
+fi
+
+# Restore IFS
+IFS=$SAVED_IFS
 
 if [ -e "initrd.gz.old" ]; then
     rm -i initrd.gz.old
@@ -69,32 +113,24 @@ echo "Making cpio archive..."
 # Method of creating cpio-format initrd file can be found here:
 # http://www.thegeekstuff.com/2009/07/how-to-view-modify-and-recreate-initrd-img/
 # Notes:
-# I support only GNU cpio and bsdcpio. Others such as Solaris cpio simply won't
-# work here.
 # -H (synonym of --format) does not work with old bsdcpio.
 # --owner (synonym of -R) might be GNU-only.
-find . | LC_ALL=C sort | sed -f ../filelist-tmp.sed | cpio -o --format newc -R root:root >../initrd
+find . \( -type d -exec printf '%s/\n' '{}' \; \) -o -print |
+    LC_ALL=C sort |
+    sed -f ../filelist-tmp.sed |
+    cpio -o --format newc -R 0:0 >../initrd
 STATUS="$?"
+
+rm ../filelist-tmp.sed
+
 if [ "$STATUS" -ne "0" ]; then
     echo "ERROR: cpio error with exit code ${STATUS}." >&2
     exit 1
 fi
 
-rm ../filelist-tmp.sed
-
 cd ..
 
 echo "Compressing..."
-
-# 7-zip is preferred because it can produce a smaller file size than gzip.
-# 7z and 7za work here, but 7zr doesn't.
-if [ `which 7z` ]; then
-    P7ZIP=7z
-elif [ `which 7za` ]; then
-    P7ZIP=7za
-else
-    P7ZIP=""
-fi
 
 if [ "X$P7ZIP" != "X" ]; then
     ${P7ZIP} a -tgzip -mx=9 initrd.gz initrd
