Redirect error messages in scripts to &2

diff --git a/cpustress/build/extract b/cpustress/build/extract
--- a/cpustress/build/extract
+++ b/cpustress/build/extract
@@ -6,20 +6,20 @@
 # <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
 #
 # Written by Explorer.
-# Last updated on 5 September 2013.
+# Last updated on 7 September 2013.
 
 # Change working directory to the directory of the script.
 cd `dirname $0`
 
 # Make sure 'build-initrd' is empty, so that we won't overwrite files.
 if [ -d "build-initrd" ] && [ "X`ls -A 'build-initrd'`" != "X" ]; then
-    echo "ERROR: Directory 'build-initrd' is not empty."
+    echo "ERROR: Directory 'build-initrd' is not empty." >&2
     exit 1
 fi
 
 if [ ! -f "initrd.gz" ]; then
     echo "File initrd.gz is not found. Please place the CPUstress initrd image in the"
-    echo "same directory as this script."
+    echo "same directory as this script." >&2
     exit 1
 fi
 
@@ -29,7 +29,7 @@ cd build-initrd
 cpio -i -m -d -u <initrd
 STATUS="$?"
 if [ "$STATUS" -ne "0" ]; then
-    echo "ERROR: cpio error with exit code ${STATUS}."
+    echo "ERROR: cpio error with exit code ${STATUS}." >&2
     exit 1
 fi
 rm initrd
